name: Publish Result PR - Docker publish

on: [workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push to GHCR
        working-directory: publish-results-pr
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login https://ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
          docker build -t ghcr.io/akosdudas/ahk-publish-results-pr:v1 .
          docker push ghcr.io/akosdudas/ahk-publish-results-pr:v1
          docker logout https://ghcr.io
