name: Publish Result PR - build

on:
  push:
    paths:
      - "publish-results-pr/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Go setup
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        working-directory: publish-results-pr
        run: go build

      - name: Test
        working-directory: publish-results-pr
        run: go test ./... -test.v
